services:
  rdgen:
    # use bryangerlach/rdgen:latest for the latest build
    #build: .
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      GHUSER: "${GHUSER}"
      GHBEARER: "${GHBEARER}"
      GENURL: "${GENURL}"
      ZIP_PASSWORD: "${ZIP_PASSWORD:-}" # O :- significa vazio se n?o definido
      GHBRANCH: "${GHBRANCH}"
      PROTOCOL: "${PROTOCOL}"
      REPONAME: "${REPONAME}"
      SH_SECRET: "${SH_SECRET:-}"
      DEBUG: "True"
    ports:
      - "45250:8000"
    dns:
      - 8.8.8.8
    volumes:
      - ./exe:/opt/rdgen/exe
      - ./png:/opt/rdgen/png
      - ./temp_zips:/opt/rdgen/temp_zips
